import './globals.css'
import type { Metadata } from 'next'
import HomeNav from '@/components/header/HomeNav';
import Link from 'next/link';
import Introduce from '@/components/header/Introduce';

export const metadata: Metadata = {
  title: '코박죽 블로그',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='flex flex-row gap-0 font-Pretendard font-normal text-lg'>
        <header className='flex flex-col w-96 h-full sticky items-center gap-8'>
          <Introduce />
          <HomeNav />
        </header>
        <main className='w-full flex-1'>
          {children}
        </main>
        <div className={'fixed right-8 bottom-8 overflow-hidden rounded-2xl bg-blue-500 px-8 py-4 text-white font-bold hover:bg-slate-700 cursor-pointer'}>
          <Link href='/post'>
            {"글 작성"}
          </Link>
        </div>
      </body>
    </html >
  )
}
